server:
  port: 8081
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 49.234.12.199
    port: 5672
    username: admin
    password: admin
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true
hello:
  world:
    word: my starter