server:
  port: 9090

spring:
  kafka:
    bootstrap-servers: 49.234.12.199:9092
    consumer:
      # 配置消费者消息offset是否自动重置(消费者重连会能够接收最开始的消息)
      auto-offset-reset: earliest
    producer:
      # 发送的对象信息变为json格式
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      # 0：这意味着producer发送数据后，不会等待broker确认，直接发送下一条数据，性能最快
      # 1：为1意味着producer发送数据后，需要等待leader副本确认接收后，才会发送下一条数据，性能中等
      # -1：这个代表的是all，意味着发送的消息写入所有的ISR集合中的副本（注意不是全部副本）后，才会发送下一条数据，性能最慢，但可靠性最强
      acks: 0
    streams:
      # 副本数量：>= 3，保证每个 分区(partition) 至少有 3 个副本。虽然造成了数据冗余，但是带来了数据的安全性。
      replication-factor: 3

kafka:
  topic:
    my-topic: my-topic
    my-topic2: my-topic2
