spring:
  ##AD\u8BA4\u8BC1
  ldap:
    ##AD\u670D\u52A1\u5668IP\uFF0C\u9ED8\u8BA4\u7AEF\u53E3389
    urls: ldap://127.0.0.1:389
    ##\u767B\u5F55\u8D26\u53F7
    username: aaaa
    ##\u5BC6\u7801
    password: bbbb
    #distinguishedName\u7684\u90E8\u5206\u8282\u70B9
    base: OU=HQ,DC=ccc,DC=com
